version: "3"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=feed
      - RABBITMQ_DEFAULT_PASS=ChangeMe
    ports:
      - 5672:5672
      - 15672:15672

  metpx-sr3:
    container_name: metpx
    build: ../../..
    environment:
      - METPX_SR3_BROKER=rabbitmq
      - METPX_SR3_BROKER_USERNAME=feed
      - METPX_SR3_BROKER_PASSWORD=ChangeMe
      - METPX_SR3_PATH=/data
      - METPX_SR3_BASEURL=http://localhost
      - METPX_SR3_LOGLEVEL=DEBUG
    volumes:
      - ./config:/home/sarra/.config/sr3:rw
      - ./:/data:rw
    depends_on:
      - rabbitmq
    command: sr3 start
