
name: run the sr_insects static_flow test.

on:
  push:
    branches:
      - v03_wip

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip3 install .
        travis/flow_autoconfig.sh
         
    - name: run Static test.
      run: |
        pwd; ls ; 
        echo hoho
        cd sr_insects/static_flow; ./flow_setup.sh
        cd sr_insects/static_flow; ./flow_limit.sh
        cd sr_insects/static_flow; ./flow_check.sh


   

